### ISSUE TITLE
Handling multiple dates/days

### ISSUE THREAD

**Issue by KartikTalwar** [uwaterloo/Scrapers#2]
Most of the edge cases have been resolved through the latest pull request #1 where the schedules are now represented as arrays. This works just fine for everything, but there is a case where the `dates` key usually containing the the days (MWF/TTh etc) also includes a date.

```
[classes] => Array
              (
                [0] => Array
                    (
                      [dates] => 04:30-06:20Th<br>10/24-10/24
                      [location] => 
                      [instructor] => 
                    )
              )
```

Since the date only comes into place when the array length is more than 1, we need to think about parsing/representing that as well. Should there be a consistent key `date` key which is blank for other classes or a key that shows up if date is present, or something else..

Thoughts?

cc/ @zachomedia, @jashp, @krisolafson, @nathanv, @cpbtklogic, @gdmalet

**Comment by jashp** [comment]
This is also a problem with some of the fields that output '&nbsp' which is essentially blank.

So showing the keys when empty is more consistent; they know which fields will be there without having to check. But removing it makes it shorter and cleaner.

I think its just a matter of preference and I'm leaning towards the first option as its easier to parse.

**Comment by zachomedia** [comment]
I agree with @jashp that &nbsp should be replaced with a blank string and leaving the keys there.

The other thing I noticed, is that on some of the output (like note), we also have the `<b>Notes:</b>` html markup show up. 

I don't know if we want to remove that markup, as it is redundant - the key already tells us that it's the note.

**Comment by KartikTalwar** [comment]
I agree with both of you guys. The code was the most basic/raw version of the scraper. It doesn't include any sanitization or additional parsing (like how v1 has building name/room number etc). The goal was to have a relatively simple function so others can jump in easily.

The primary goal was to handle the edge cases; now we can move to formatting response and adding the missing information. #3, #4, #6
